### ISSUE TITLE
python chat.py <User> does not let me chat to <User>

### ISSUE THREAD

**Issue by tomasi-o** [zvovov/whatsapp-web#2]
installed whatsapp-web like you described on https://zvovov.github.io/whatsapp-cli. Installing pip following your instructions on https://github.com/zvovov/whatsapp-web, but had to install it via macports. 

Starting a chat with `python chat.py Username` did result in the error below:
`shyMac:whatsapp-web tomasio$ python chat.py Band test
Traceback (most recent call last):
  File "chat.py", line 11, in <module>
    from selenium import webdriver
ImportError: No module named selenium`

Thus I installed selenium using
`sudo easy_install selenium` (using a built-in installer procedure on MacOS X)

Starting a chat with `python chat.py Username` results now in:
`shyMac:whatsapp-web tomasio$ python chat.py Band

	Press Ctrl+C again to exit.`

Do you have got any clue what I could have done wrong? Thank you in advance for your efforts.

**Comment by zvovov** [comment]
It could be one of the two things:

- selenium didn't install properly
  Try to verify that selenium is installed. (using `pip list` if you're using `pip`, or a similar command for macports)
- chromedriver is not working as it should
  For this, check if chat.py file contains valid path to the chromedriver executable file.

**Comment by nurdinfuqoha** [comment]
hi zvovov, i also have the same problem, i have two version of Python, 2.6 and 3.4 
when i run script for sending message, i only get "Press Ctrl+C again to exit" 
i dont know how the selenium is installed properly for, either for python 2.6 or 3.4

can you help me with installing selenium for python 3?

**Comment by thetemplar** [comment]
Me too,
when starting the script I only get "Press Ctrl+C again to exit".
Both dependencies are installed correctly.

I am using Python 3.

**Comment by zvovov** [comment]
@tomasi-o @idemenef @thetemplar It looks like "Press Ctrl+C again to exit" error was related to ChromeDriver version not being compatible with Chrome Browser. Verify, from the ChromeDriver download page, that the ChromeDriver version you downloaded supports Chrome version that is installed in your system.
I have also added this in the README.
Let me know, if the problem persists.

**Comment by setiaji** [comment]
Just downloaded everything you said here, and this is the error message:   File "chat.py", line 197
    sys.exit(print(e, decorateMsg("\n\tChromedriver Error. Read the above error (if any), then\n\tCheck if installed chromedriver version is compatible with installed Chrome vesion.", bcolors.WARNING)))
                 ^
SyntaxError: invalid syntax

I am using lates chrome browser and also latest chromedriver..need your advice to run...thanks before..

**Comment by zvovov** [comment]
@setiaji use python3.

**Comment by tomasi-o** [comment]
I have to reopen this issue, as with a new version of Chrome (Version 64.0.3282.186 (official build) (64-Bit)) and the appropriate chromedriver version (ChromeDriver 2.35) whatsapp-web cli crashes after taking these steps:

1. iMac:whatsapp-web _username_$ python chat.py _WhatsappUser_
2. (Google Chrome is started, loggin into whatsapp-web capturing the code on the Webpage /w my smartphone)
3. my Terminal asks: `	Phone connected? y/n:`
4. As soon as I type in 'y', Google Chrome crashes and I get this error message:
5. `Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="main"]/header//div[contains(@class, "chat-main")]"}
  (Session info: chrome=64.0.3282.186)
  (Driver info: chromedriver=2.35.528157 (4429ca2590d6988c0745c24c8858745aaaec01ef),platform=Mac OS X 10.11.6 x86_64)

	Chromedriver Error. Read the above error (if any), then
	Check if installed chromedriver version is compatible with installed Chrome vesion.`

The path in chat.py which points to the location of the chromedriver binary file is correct, although the installed versions of python and selenium differ: 
Python 3.6.4
selenium 3.4.0 (which is the selenium version which gets installed after using the `pip install` command)

Maybe you can help me out again? Thank you in advance!
