### ISSUE TITLE
invalid syntax on line 249 of chat.py

### ISSUE THREAD

**Issue by anabis** [zvovov/whatsapp-web#26]
It works after commenting the lines 249 & 250. I  know nothing about python but I couldn't see the syntax error.
`hugo@brun:~/sources$ python whatsapp-web/chat.py`
`  File "whatsapp-web/chat.py", line 249`
`    sys.exit(print(e, decorateMsg("\n\tChromedriver Error. Read the above error (if any), then\n\tCheck ``if installed chromedriver version is compatible with installed Chrome version.", bcolors.WARNING)))`

**Comment by Neto223317** [comment]
execute:
python3 whatsapp-web/chat.py

 I had this message with this command
python3 chat.py 
Error: Missing name of contact/group
python chat.py <name>
if works to you, share your results, pls

**Comment by luigisalas** [comment]
Remember install selenium for python3

pip3 install selenium

**Comment by robinsonmas** [comment]
hi ,  i have this error . 


""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
C:\chat>chat.py robinsonmas
Traceback (most recent call last):
  File "C:\chat\chat.py", line 243, in <module>
    main()
  File "C:\chat\chat.py", line 54, in main
    chrome_data_dir_directory = "{0}/.chrome/data_dir/whatsapp_web_cli".format(os.environ['HOME'])
  File "C:\Users\robinsonmas.DC\AppData\Local\Programs\Python\Python37-32\lib\os.py", line 678, in __getitem__
    raise KeyError(key) from None
KeyError: 'HOME'


""""""""""""""""""""""""""""""""""""""""""""

any posible solution , ?> 


Thanks  for your help .

**Comment by zvovov** [comment]
The HOME environment variable is not available on Windows.

As a workaround, you can either comment out these [3 lines from chat.py](https://github.com/zvovov/whatsapp-web/blob/9b6b4e341783364bcd6c0c55430ddae03d2ff964/chat.py#L51) 
```
chrome_data_dir_directory = "{0}/.chrome/data_dir/whatsapp_web_cli".format(os.environ['HOME'])
if not os.path.exists(chrome_data_dir_directory):
    os.makedirs(chrome_data_dir_directory)
```
This would remove the functionality of auto sign-in and you would have to scan the QR code everytime you run the script.

Alternatively, you can look at this solution to figure out how to access the USERPROFILE variable [as described here](https://stackoverflow.com/a/14742225)

I don't have access to a Windows machine at the moment. Let me know how it goes
