### ISSUE TITLE
Exits when pressing 'y'

### ISSUE THREAD

**Issue by gabrieljim** [zvovov/whatsapp-web#3]
I'm hyped for this, so I hope i can get some fix
I'm on Lubuntu 16.04, did every step, but when I'm asked if the phone is connected and press y, I get the error on the pic
![bug](https://cloud.githubusercontent.com/assets/21229805/26036398/dc9f8ab4-38aa-11e7-9acf-1c0981ab6ad6.png)

What could i do?

**Comment by zvovov** [comment]
This error seems interesting. Looks like console is not able to take user input for some reason.
Can you pull the changes and try again?

**Comment by gabrieljim** [comment]
Uh, I'm not sure if this is about the change you did or I did something wrong with reinstalling.
Now when I initiate the program i get the error on the pic
![2017-05-21-121537_1021x90_scrot](https://cloud.githubusercontent.com/assets/21229805/26285501/734eb448-3e1f-11e7-834a-cd09819385b0.png)

I also attach a screencap of my Chromium version (could it be that I'm using Chromium instead of official Chrome?)

![2017-05-21-121835_507x225_scrot](https://cloud.githubusercontent.com/assets/21229805/26285508/a79758ea-3e1f-11e7-83fc-df66e63c7952.png)

And also attaching a screencap of the location of chromedriver as well as the path on "chat.py"

![2017-05-21-122101_615x310_scrot](https://cloud.githubusercontent.com/assets/21229805/26285550/2115e2f4-3e20-11e7-9079-5fe224e272f1.png)

I hope it's an error on my side, haha

**Comment by zvovov** [comment]
Hey @gabrieljim can you check the python version you're using? The script works with python 3 only, not 2.

**Comment by gabrieljim** [comment]
Okay, i changed
python chat.py
to python3 chat.py
Now it says it doesn't find the module selenium, even though i did "pip install selenium"
I assume it installs it to python 2 so I'm dowloading pip3, I'll report back after that's done.

**Comment by gabrieljim** [comment]
Great! It's fixed, I can send and receive messages.

Just one more little thing, after connecting, after any command I input, I get:

![2017-05-21-133731_1018x442_scrot](https://cloud.githubusercontent.com/assets/21229805/26286104/e68df710-3e2a-11e7-8956-feeb09ffb252.png)
Doesn't affect the script whatsoever, I'm just informing you, after that it doesn't appear again, or it hasn't so far

Anyways, thanks for your help! I'm glad this worked.

**Comment by zvovov** [comment]
Well, have you tried turning it off and on again. :smile: 
The error shouldn't persist.

**Comment by gabrieljim** [comment]
The problem persists, though
