### ISSUE TITLE
Use in headless server

### ISSUE THREAD

**Issue by qhpw** [zvovov/whatsapp-web#32]
Hi @zvovov, first of all thank you for sharing this and awesome work.

Can I check if this script is meant to be used from command line on a local machine? I wonder if actually I can use this in a remote headless server. Thanks.

**Comment by zvovov** [comment]
Hi,

Thanks for using the project.
You can use this project to run WhatsApp through the terminal on a remote
machine provided that machine has a GUI and has Chrome installed on it.

**Comment by francesquini** [comment]
I use it on a remote headless server using X virtual framebuffer (xvfb).
It works fine...

**Comment by zvovov** [comment]
Great
