### ISSUE TITLE
Not Receiving Messages: UnboundLocalError: local variable 'first_msg' referenced before assignment

### ISSUE THREAD

**Issue by Jonzai** [zvovov/whatsapp-web#34]
Sending messages work, but we get an error that seems to point to changes in how messages are stored (I saw the same note in another issue posted here).

It points to line 137:

        if first_msg: # if one or more messages exist 

But maybe the variable declaration under a 'try:' block is not working:

   try:
            first_msg = all_msgs_text_only[0]

Where all_msgs_text is defined as:

        # get incoming msgs
        all_msgs_text_only = driver.find_elements(By.XPATH, '//*[@id="main"]//div[contains(@class, "msg")]//span[contains(@dir, "ltr")]')

**Comment by zvovov** [comment]
The code has since been updated. This should be fixed. Please share the error traceback if you are still facing this error
