### ISSUE TITLE
Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="side"]//input"}   (Session info: headless chrome=84.0.4147.89)

### ISSUE THREAD

**Issue by ramdoni** [zvovov/whatsapp-web#37]
`Phone connected? y/n: y`

i have error when i input 'y'

`Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="side"]//input"}
  (Session info: headless chrome=84.0.4147.89)
Chromedriver Error. Read the above error (if any), then
Check if installed chromedriver version is compatible with installed Chrome version.`

**Comment by tigger04** [comment]
yep same here
```

	Phone connected? y/n: y
Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="side"]//input"}
  (Session info: chrome=85.0.4183.83)
 
	Chromedriver Error. Read the above error (if any), then
	Check if installed chromedriver version is compatible with installed Chrome version.
```

**Comment by farshid616** [comment]
Same for me

Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="side"]//input"}
  (Session info: chrome=86.0.4240.75)
 
	Chromedriver Error. Read the above error (if any), then
	Check if installed chromedriver version is compatible with installed Chrome version.

But the driver and the chrome are in the same version

**Comment by zvovov** [comment]
This has been fixed https://github.com/zvovov/whatsapp-web/commit/2485e03663631506efab4ff705170caca99eb509
