### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by tigger04** [zvovov/whatsapp-web#38]
I get is ... WhatsApp don't like this kind of project, so it's whack-a-mole for every time we get one working.

This one seemed to be the most promising amongst the graveyard of dead WhatsApp-CLI tools out there. I gave it a try 1 or 2 months ago, and, well, after far too many hours, I came out with nothing. And that made me sad.

Just stumbled across this again, doesn't look like anything has changed.

I'm just confused as to what's going on here - on the one hand there hasn't been a commit for 2 years. On the other hand the issues board seems pretty active, but (unless I've missed one) I don't see anyone actually getting the thing to work.

So can we do the honourable thing, and put an end to the grief and sadness of the WhatsAPP-CLI-dreamers, and just put this thing out of its misery and close the project.

**Comment by zvovov** [comment]
Hey @tigger04 I get the reasoning behind your impassioned message. I had not been able to actively keep up with the development of the project. However, other folks that saw value in the project continued to contribute to the code base and the issues page. The code works now and you should give it a try.

This project is very much active.
