### ISSUE TITLE
When i received a message. This error is thrown

### ISSUE THREAD

**Issue by vyshark** [zvovov/whatsapp-web#4]
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "chat.py", line 107, in startGetMsg
    incoming_scheduler.run()
  File "/usr/lib/python3.6/sched.py", line 154, in run
    action(*argument, **kwargs)
  File "chat.py", line 141, in getMsg
    if curr_msg_id[:4] == 'true' or curr_msg_id == last_printed_msg_id:
TypeError: 'NoneType' object is not subscriptable

**Comment by zvovov** [comment]
Make sure all dependencies are installed. Check the README to know the versions on which this has been tested.

**Comment by sarfraznawaz2005** [comment]
Same error me too with Python 3.6.3, works fine on sending though but not receiving. Using Windows 8.

**Comment by sarfraznawaz2005** [comment]
I think there have been DOM changes in whatsapp web which is why receiving is not working anymore.

**Comment by sarfraznawaz2005** [comment]
I created my own version of whatsapp cli: https://github.com/sarfraznawaz2005/whatspup 😄

**Comment by sealabr** [comment]
nice

**Comment by zvovov** [comment]
Was due to whatsapp web DOM changes. Fixed
