### ISSUE TITLE
is this the same as sspeedy99 / whatsapp-cli ?

### ISSUE THREAD

**Issue by pascalbrax** [zvovov/whatsapp-web#40]
I was googling for a CLI app to automate whatsapp messages and found this github, but also I've found @sspeedy99 github with a very similar chat.py codebase.

Is this the fork of speedy's code or is speedy the fork of this one? I'm confused.

**Comment by sspeedy99** [comment]
My code is forked from @zvovov . This is the original repository, however I do not know that it is maintained.
