### ISSUE TITLE
python chat.py test downt work 

### ISSUE THREAD

**Issue by Marvin-Media** [zvovov/whatsapp-web#7]
python chat.py test
  File "chat.py", line 209
    sys.exit(print(e, decorateMsg("\n\tChromedriver Error. Read the above error (if any), then\n\tCheck if installed chromedriver version is compatible with installed Chrome vesion.", bcolors.WARNING)))
                 ^
SyntaxError: invalid syntax

**Comment by masterwaqar** [comment]
pip3 install chromedriver

**Comment by mostrosonido** [comment]
Same Problem (Ubuntu 15 (x64):
File "chat.py", line 209
sys.exit(print(e, decorateMsg("\n\tChromedriver Error. Read the above error (if any), then\n\tCheck if installed chromedriver version is compatible with installed Chrome vesion.", bcolors.WARNING)))
^
SyntaxError: invalid syntax

**Comment by zvovov** [comment]
@Marvin-Media  @mostrosonido Use python3, not python2
 check your python version by typing "python --version" and "python3 --version". Whichever command returns python 3.x, use that to run this script. If none of these return python 3.x, install python 3 on your system. **This script will only work with python 3, and not with python 2**
